apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp
  namespace: sampleapp
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  labels:
    name: guestbook
spec:
  project: default
  source:
    repoURL: https://github.com/agentp2210/java-AKS.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: helm/sampleapp

    # helm specific config
    helm:
      passCredentials: false # If true then adds --pass-credentials to Helm commands to pass credentials to all domains
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "nginx-ingress.controller.service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
        value: argocd.anhalan.nl
      - name: "ingress.annotations.kubernetes\\.io/tls-acme"
        value: "true"
        forceString: true # ensures that value is treated as a string
      releaseName: sampleapp
      valueFiles:
      - values.yaml
      ignoreMissingValueFiles: false

      values: |
        ingress:
          enabled: true
          path: /
          hosts:
            - argocd.anhalan.nl
  destination:
    server: https://kubernetes.default.svc
    namespace: sampleapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
