apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-config
  name: mysql-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi