apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-petclinic.fullname" . }}
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port | quote }}
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    {{- include "spring-petclinic.selectorLabels" . | nindent 4 }}
