apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: ghcr.io/argoproj/argo-helm  # note: the oci:// syntax is not included.
    targetRevision: 7.7.0   # To find the latest chart version run: 'helm search hub argo-cd'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true