{
 "title": "Cluster Overview",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 }, "options": { "content": "<center><h1> DLF" } },
  {
   "title": "TLS cert days until expire",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((certmanager_certificate_expiration_timestamp_seconds-time())/60/60/24)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU commitment / usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\"})*100",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=''}[10m]))/sum(rate(container_cpu_system_seconds_total{container!=''}[10m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"})*100",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container!=''}) / sum(kube_node_status_allocatable{resource=\"memory\"})*100",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}