{
 "title": "Clusters overview - Exported",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 1, "x": 0, "y": 0 }, "options": { "content": "<center><h1> DLF\n\n" } },
  {
   "title": "TLS cert days until expire",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((certmanager_certificate_expiration_timestamp_seconds-time())/60/60/24)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU commitment / usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\".*worker.*\"}) / sum(kube_node_status_allocatable{resource=\"cpu\",node=~\".*worker.*\"})*100",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\".*worker-.\",container!=''}[10m]))/sum(rate(container_cpu_system_seconds_total{instance=~\".*worker-.\",container!=''}[10m]))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",node=~\".*worker.*\"}) / sum(kube_node_status_allocatable{resource=\"memory\",node=~\".*worker.*\"})*100",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\".*worker-.\",container!=''}) / sum(kube_node_status_allocatable{resource=\"memory\",node=~\".*worker.*\"})*100",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network utilization",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='ens192'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='ens192'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage used top3 (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,kubelet_volume_stats_used_bytes/kubelet_volume_stats_capacity_bytes*100)",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data storage used (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"minio\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"minio\"}*100",
     "legendFormat": "Apps"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-loki-0\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"storage-loki-0\"}*100",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data storage used (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"minio\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"minio\"}*100",
     "legendFormat": "Apps"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-loki-0\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"storage-loki-0\"}*100",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data storage used (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"minio\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"minio\"}*100",
     "legendFormat": "Apps"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-loki-0\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"storage-loki-0\"}*100",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data storage used (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"minio\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"minio\"}*100",
     "legendFormat": "Apps"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-loki-0\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"storage-loki-0\"}*100",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data storage used (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"minio\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"minio\"}*100",
     "legendFormat": "Apps"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-loki-0\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"storage-loki-0\"}*100",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data storage used (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"minio\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"minio\"}*100",
     "legendFormat": "Apps"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-loki-0\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"storage-loki-0\"}*100",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data storage used (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"minio\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"minio\"}*100",
     "legendFormat": "Apps"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-loki-0\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"storage-loki-0\"}*100",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{interface='eth0'}[5m]))/300*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods pulse",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data storage used (%)",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"minio\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"minio\"}*100",
     "legendFormat": "Apps"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"storage-loki-0\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"storage-loki-0\"}*100",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Sync failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pending resources",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})+sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\"})+sum(kube_persistentvolume_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{ phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}